In [27]:
import json
import numpy as np
import pandas as pd
import re
import itertools
import glob

class myClass (object):
  def __init__(self, f, data):
    self.file_name = f
    self.data = data
  
  def __lt__(self, other):
    return self.file_name < other.file_name

data_list = []

for f in glob.glob('log*'):

  with open(f) as x:
    data_list.append(myClass(f , json.load(x)))

columns_header = ["4x4", "5x5", "6x6", "7x7", "8x8"]

row_header_1 = ["60", "70", "72", "74", "76", "78", "80", "90"]
row_header_2 = ["avg outcome", "std outcome", "grabbed gold","percentage grabbed gold", "avg with gold", "std with gold", "home without gold", "percentage home without gold", "avg without gold", "std without gold", "died", "percentage died", "avg died", "std died"]

row_header_index1 = list(itertools.chain.from_iterable(itertools.repeat(x, len(row_header_2)) for x in row_header_1))
row_header_index2 = row_header_2 * len(row_header_1)

dataframe_dict = {'threshold': row_header_index1, 'stat_data': row_header_index2,
        '4x4': ["a" for i in range(len(row_header_1)*len(row_header_2))],
        '5x5': ["a" for i in range(len(row_header_1)*len(row_header_2))],
        '6x6': ["a" for i in range(len(row_header_1)*len(row_header_2))],
        '7x7': ["a" for i in range(len(row_header_1)*len(row_header_2))],
        '8x8': ["a" for i in range(len(row_header_1)*len(row_header_2))]
         }

dataframe = pd.DataFrame(dataframe_dict)
dataframe = dataframe.set_index(['threshold', 'stat_data'])

for data_entry in sorted(data_list):
  # print("*" * 30)
  data = data_entry.data
  filename = data_entry.file_name
  # print(filename)
  outcomes = []
  alives = []
  outcomes_alive_with_gold = []
  outcomes_alive_without_gold = []
  outcomes_died = []
  for i in range (len(data)):

    outcome = data[i]['outcome']
    alive = data[i]['alive']

    outcomes.append(outcome)
    alives.append(alive)

    if data[i]['alive']:
      if "GRAB" in data[i]['moves']:
        outcomes_alive_with_gold.append(outcome)
      else:
        outcomes_alive_without_gold.append(outcome)
    else:
      outcomes_died.append(outcome)

  o = np.array(outcomes)
  o_gold = np.array(outcomes_alive_with_gold)
  o_not_gold = np.array(outcomes_alive_without_gold)
  o_died = np.array(outcomes_died)

  std = np.std(o)
  std_gold = np.std(o_gold)
  std_not_gold = np.std(o_not_gold)
  std_died = np.std(o_died)

  avg_outcomes = np.mean(o)
  avg_gold = np.mean(o_gold)
  avg_not_gold = np.mean(o_not_gold)
  avg_died = np.mean(o_died)

  n_gold = len(o_gold)
  perc_gold = (n_gold/len(data))*100
    
  n_no_gold = len(o_not_gold)
  perc_no_gold = (n_no_gold/len(data))*100
    
  n_died = len(o_died)
  perc_died = (n_died/len(data))*100

  # print("std = %f" %std)
  # print("avg outcome = %f" %avg_outcomes)
  # print("died = %i" %died)
  # print("percentage died = %f" %perc_died)
  # #print("min outcome = %i" %min_out)
  # #print("max outcome = %i" %max_out)
  # print("std alive with gold = %f" %std_gold)
  # print("avg outcome alive with gold = %f" %avg_gold)
  # print("std alive without gold = %f" %std_not_gold)
  # print("avg outcome alive without gold = %f" %avg_not_gold)
  # print("std died = %f" %std_died)
  # print("avg outcome died = %f" %avg_died)

  dataframe.loc[(data_entry.file_name[8:10], "avg outcome"), [data_entry.file_name[4:7]]] = avg_outcomes
  dataframe.loc[(data_entry.file_name[8:10], "std outcome"), [data_entry.file_name[4:7]]] = std
  dataframe.loc[(data_entry.file_name[8:10], "grabbed gold"), [data_entry.file_name[4:7]]] = n_gold
  dataframe.loc[(data_entry.file_name[8:10], "percentage grabbed gold"), [data_entry.file_name[4:7]]] = perc_gold
  dataframe.loc[(data_entry.file_name[8:10], "avg with gold"), [data_entry.file_name[4:7]]] = avg_gold
  dataframe.loc[(data_entry.file_name[8:10], "std with gold"), [data_entry.file_name[4:7]]] = std_gold
  dataframe.loc[(data_entry.file_name[8:10], "home without gold"), [data_entry.file_name[4:7]]] = n_no_gold
  dataframe.loc[(data_entry.file_name[8:10], "percentage home without gold"), [data_entry.file_name[4:7]]] = perc_no_gold
  dataframe.loc[(data_entry.file_name[8:10], "avg without gold"), [data_entry.file_name[4:7]]] = avg_not_gold
  dataframe.loc[(data_entry.file_name[8:10], "std without gold"), [data_entry.file_name[4:7]]] = perc_no_gold
  dataframe.loc[(data_entry.file_name[8:10], "died"), [data_entry.file_name[4:7]]] = n_died
  dataframe.loc[(data_entry.file_name[8:10], "percentage died"), [data_entry.file_name[4:7]]] = perc_died
  dataframe.loc[(data_entry.file_name[8:10], "avg died"), [data_entry.file_name[4:7]]] = avg_died
  dataframe.loc[(data_entry.file_name[8:10], "std died"), [data_entry.file_name[4:7]]] = std_died

/Users/marcodpro/opt/anaconda3/envs/online_wumpus/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Users/marcodpro/opt/anaconda3/envs/online_wumpus/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/Users/marcodpro/opt/anaconda3/envs/online_wumpus/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/Users/marcodpro/opt/anaconda3/envs/online_wumpus/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/marcodpro/opt/anaconda3/envs/online_wumpus/lib/python3.8/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

In [17]:
dataframe

                                 4x4      5x5      6x6      7x7      8x8
threshold stat_data
60        avg outcome        344.202  234.392  102.904  -14.722  -56.109
          std outcome        637.471  688.408  705.558  716.077  729.775
          avg with gold            a        a        a        a        a
          std with gold      13.4131  18.3745  26.1252  34.3123  38.1691
          avg without gold         a        a        a        a        a
...                              ...      ...      ...      ...      ...
78        home without gold       45       71       60       89       84
80        grabbed gold             0        0        0        0        0
          home without gold        0        0        0        0        0
90        grabbed gold             0        0        0        0        0
          home without gold        0        0        0        0        0

[96 rows x 5 columns]

In [61]:
#pd.set_option("display.max_rows", None, "display.max_columns", None)
avg_result = dataframe.xs('avg outcome', level='stat_data')

In [65]:
avg_result = dataframe.xs('avg outcome', level='stat_data').copy()
avg_result['average'] = avg_result.mean(axis=1)
avg_result

               4x4      5x5      6x6      7x7      8x8   average
threshold
60         344.202  234.392  102.904  -14.722  -56.109  122.1333
70         334.069   256.19  182.768  120.336   65.394  191.7515
72         351.238   276.18  193.095  126.244   47.048  198.7610
74         337.555  265.522  180.433  153.147   60.656  199.4625
76         353.359  251.726  188.972  154.618   78.204  205.3759
78         324.248  268.075  159.818  119.334    85.63  191.4209
80         335.193  264.608  195.661  164.555  124.257  216.8549
90          348.55   263.38  207.721  179.306  112.074  222.2062

In [66]:
print(avg_result.to_latex(index=True))

\begin{tabular}{llllllr}
\toprule
{} &      4x4 &      5x5 &      6x6 &      7x7 &      8x8 &   average \\
threshold &          &          &          &          &          &           \\
\midrule
60        &  344.202 &  234.392 &  102.904 &  -14.722 &  -56.109 &  122.1333 \\
70        &  334.069 &   256.19 &  182.768 &  120.336 &   65.394 &  191.7515 \\
72        &  351.238 &   276.18 &  193.095 &  126.244 &   47.048 &  198.7610 \\
74        &  337.555 &  265.522 &  180.433 &  153.147 &   60.656 &  199.4625 \\
76        &  353.359 &  251.726 &  188.972 &  154.618 &   78.204 &  205.3759 \\
78        &  324.248 &  268.075 &  159.818 &  119.334 &    85.63 &  191.4209 \\
80        &  335.193 &  264.608 &  195.661 &  164.555 &  124.257 &  216.8549 \\
90        &   348.55 &   263.38 &  207.721 &  179.306 &  112.074 &  222.2062 \\
\bottomrule
\end{tabular}

In [69]:
perc_died = dataframe.xs('percentage died', level='stat_data').copy()
perc_died['died'] = perc_died.mean(axis=1)
perc_died

            4x4   5x5   6x6   7x7   8x8   died
threshold
60         9.05  14.5  19.5  24.9  27.8  19.15
70          1.6   4.8   6.7   8.7   9.7   6.30
72         2.25   3.6     6   9.1  11.6   6.51
74          1.8  3.35   6.4   6.5  10.3   5.67
76          1.8   4.2     5   5.8   9.7   5.30
78         2.25  3.55     6   8.9   8.4   5.82
80            0     0     0     0     0   0.00
90            0     0     0     0     0   0.00

In [70]:
print(perc_died.to_latex(index=True))

\begin{tabular}{llllllr}
\toprule
{} &   4x4 &   5x5 &   6x6 &   7x7 &   8x8 &   died \\
threshold &       &       &       &       &       &        \\
\midrule
60        &  9.05 &  14.5 &  19.5 &  24.9 &  27.8 &  19.15 \\
70        &   1.6 &   4.8 &   6.7 &   8.7 &   9.7 &   6.30 \\
72        &  2.25 &   3.6 &     6 &   9.1 &  11.6 &   6.51 \\
74        &   1.8 &  3.35 &   6.4 &   6.5 &  10.3 &   5.67 \\
76        &   1.8 &   4.2 &     5 &   5.8 &   9.7 &   5.30 \\
78        &  2.25 &  3.55 &     6 &   8.9 &   8.4 &   5.82 \\
80        &     0 &     0 &     0 &     0 &     0 &   0.00 \\
90        &     0 &     0 &     0 &     0 &     0 &   0.00 \\
\bottomrule
\end{tabular}